[package]
name = "system_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
leptos = { version = "0.6", default-features = false }
serde_json = "1"
shrs_core_headless = { path = "../shrs_core_headless" }
system_shell_contract = { path = "../system_shell_contract" }
