[workspace]
members = [
  "crates/apps/calculator",
  "crates/desktop_runtime",
  "crates/site",
  "crates/apps/explorer",
  "crates/apps/notepad",
  "crates/apps/terminal",
  "xtask",
]
resolver = "2"
