[package]
name = "desktop_app_explorer"
version = "0.1.0"
edition = "2021"

[features]
default = ["csr"]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate", "csr"]
ssr = ["leptos/ssr"]

[dependencies]
leptos = { version = "0.6", default-features = false }
serde_json = "1"

