[package]
name = "platform_host"
version = "0.1.0"
edition = "2021"

[dependencies]
desktop_app_contract = { path = "../desktop_app_contract", default-features = false }
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
futures = "0.3"
